version: 0.0
os: linux
files:
  - source: /project/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: www-data
    - location: scripts/start_server
      timeout: 300
      runas: www-data
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: www-data

